// Auto-generated blog index - DO NOT EDIT MANUALLY
// This file is generated by buildblog.py

export interface BlogMeta {
  title: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  authorAvatar: string;
  heroImage?: string;
  tags: string[];
  slug: string;
  excerpt?: string;
  featuredOnHome?: boolean;
  featuredOnBlog?: boolean;
  displayOrder?: number;
  external?: boolean;
  externalUrl?: string;
}

export interface BlogIndexEntry {
  slug: string;
  component: string | null;
  meta: BlogMeta;
}

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "building-scalable-microservices",
    "component": "BuildingScalableMicroservicesPage",
    "meta": {
      "title": "Building Scalable Microservices with Node.js",
      "category": "BACKEND",
      "date": "Oct 15, 2025",
      "readTime": "8 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1593442257276-1895e27c8ed6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODQ5MDI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "Node.js",
        "Microservices",
        "Architecture",
        "Backend"
      ],
      "slug": "building-scalable-microservices",
      "excerpt": "Learn how to design and implement microservices architecture that can handle millions of requests with minimal latency.",
      "featuredOnHome": true,
      "featuredOnBlog": true,
      "displayOrder": 2,
      "external": false,
      "externalUrl": null
    }
  },
  {
    "slug": "deep-learning-on-medium",
    "component": null,
    "meta": {
      "title": "Deep Learning Fundamentals: A Complete Guide",
      "category": "MACHINE LEARNING",
      "date": "Oct 18, 2025",
      "readTime": "12 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1677442136019-21780ecad995?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
      "tags": [
        "Deep Learning",
        "Neural Networks",
        "PyTorch",
        "AI"
      ],
      "slug": "deep-learning-on-medium",
      "excerpt": "A comprehensive guide to understanding deep learning fundamentals, from neural networks to advanced architectures like transformers and CNNs.",
      "featuredOnHome": true,
      "featuredOnBlog": false,
      "displayOrder": 1,
      "external": true,
      "externalUrl": "https://medium.com/@yourusername/deep-learning-fundamentals"
    }
  },
  {
    "slug": "pytorch-certification-course",
    "component": "PytorchCertificationCoursePage",
    "meta": {
      "title": "Building PyTorch Foundation's Official Certification Course",
      "category": "MACHINE LEARNING",
      "date": "Oct 21, 2025",
      "readTime": "10 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "/src/assets/blogs/Pytorch_Course/10_21_2025_Reflection_Post/Neural_Network_diagram.png",
      "tags": [
        "PyTorch",
        "Deep Learning",
        "Education",
        "IBM Research",
        "Certification"
      ],
      "slug": "pytorch-certification-course",
      "excerpt": "How I designed 7 hands-on PyTorch labs for the official PyTorch Foundation Certification program during my internship at IBM Research, making deep learning accessible through visual illustrations and practical examples.",
      "featuredOnHome": true,
      "featuredOnBlog": true,
      "displayOrder": 0,
      "external": false,
      "externalUrl": null
    }
  },
  {
    "slug": "react-performance-optimization",
    "component": "ReactPerformanceOptimizationPage",
    "meta": {
      "title": "React Performance Optimization Techniques",
      "category": "FRONTEND",
      "date": "Oct 5, 2025",
      "readTime": "6 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1711599813951-89297e6201a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODI4MTkxfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "React",
        "Performance",
        "Optimization",
        "Frontend"
      ],
      "slug": "react-performance-optimization",
      "excerpt": "Discover advanced patterns and techniques to make your React applications blazingly fast and responsive.",
      "featuredOnHome": false,
      "featuredOnBlog": false,
      "displayOrder": 3,
      "external": false,
      "externalUrl": null
    }
  }
];

// Import all generated blog page components
import { BuildingScalableMicroservicesPage } from "./BuildingScalableMicroservicesPage";
import { PytorchCertificationCoursePage } from "./PytorchCertificationCoursePage";
import { ReactPerformanceOptimizationPage } from "./ReactPerformanceOptimizationPage";

export const BLOG_COMPONENTS = {
  "building-scalable-microservices": BuildingScalableMicroservicesPage,
  "pytorch-certification-course": PytorchCertificationCoursePage,
  "react-performance-optimization": ReactPerformanceOptimizationPage,
};
