// Auto-generated blog index - DO NOT EDIT MANUALLY
// This file is generated by buildblog.py

export interface BlogMeta {
  title: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  authorAvatar: string;
  heroImage?: string;
  tags: string[];
  slug: string;
}

export interface BlogIndexEntry {
  slug: string;
  component: string;
  meta: BlogMeta;
}

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "building-scalable-microservices",
    "component": "BuildingScalableMicroservicesPage",
    "meta": {
      "title": "Building Scalable Microservices with Node.js",
      "category": "BACKEND",
      "date": "Oct 15, 2025",
      "readTime": "8 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      "heroImage": "https://images.unsplash.com/photo-1593442257276-1895e27c8ed6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODQ5MDI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "Node.js",
        "Microservices",
        "Architecture",
        "Backend"
      ],
      "slug": "building-scalable-microservices"
    }
  },
  {
    "slug": "react-performance-optimization",
    "component": "ReactPerformanceOptimizationPage",
    "meta": {
      "title": "React Performance Optimization Techniques",
      "category": "FRONTEND",
      "date": "Oct 5, 2025",
      "readTime": "6 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      "heroImage": "https://images.unsplash.com/photo-1711599813951-89297e6201a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODI4MTkxfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "React",
        "Performance",
        "Optimization",
        "Frontend"
      ],
      "slug": "react-performance-optimization"
    }
  }
];

// Import all generated blog page components
import { BuildingScalableMicroservicesPage } from "./BuildingScalableMicroservicesPage";
import { ReactPerformanceOptimizationPage } from "./ReactPerformanceOptimizationPage";

export const BLOG_COMPONENTS = {
  "building-scalable-microservices": BuildingScalableMicroservicesPage,
  "react-performance-optimization": ReactPerformanceOptimizationPage,
};
