// Auto-generated blog index - DO NOT EDIT MANUALLY
// This file is generated by buildblog.py

export interface BlogMeta {
  title: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  authorAvatar: string;
  heroImage?: string;
  tags: string[];
  slug: string;
  excerpt?: string;
  featuredOnHome?: boolean;
  featuredOnBlog?: boolean;
  displayOrder?: number;
  external?: boolean;
  externalUrl?: string;
  active?: boolean;
}

export interface BlogIndexEntry {
  slug: string;
  component: string | null;
  meta: BlogMeta;
}

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "building-scalable-microservices",
    "component": "BuildingScalableMicroservicesPage",
    "meta": {
      "title": "Building Scalable Microservices with Node.js",
      "category": "BACKEND",
      "date": "Oct 15, 2025",
      "readTime": "8 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1593442257276-1895e27c8ed6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODQ5MDI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "Node.js",
        "Microservices",
        "Architecture",
        "Backend"
      ],
      "slug": "building-scalable-microservices",
      "excerpt": "Learn how to design and implement microservices architecture that can handle millions of requests with minimal latency.",
      "featuredOnHome": true,
      "featuredOnBlog": false,
      "displayOrder": 2,
      "external": false,
      "externalUrl": null
    }
  },
  {
    "slug": "pytorch-certification-course",
    "component": "PytorchCertificationCoursePage",
    "meta": {
      "title": "Contributing to PyTorch Foundation's Certification Training Course",
      "category": "MACHINE LEARNING",
      "date": "Oct 21, 2025",
      "readTime": "15 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "/blogs/Pytorch_Course/10_21_2025_Reflection_Post/Neural_Network_diagram.png",
      "tags": [
        "PyTorch",
        "Deep Learning",
        "Education",
        "IBM Research",
        "Certification"
      ],
      "slug": "pytorch-certification-course",
      "excerpt": "How I designed 7 hands-on PyTorch labs for the official PyTorch Foundation Certification program during my internship at IBM Research, making deep learning accessible through visual illustrations and practical examples.",
      "featuredOnHome": true,
      "featuredOnBlog": true,
      "displayOrder": 3,
      "external": false,
      "externalUrl": null
    }
  },
  {
    "slug": "react-performance-optimization",
    "component": "ReactPerformanceOptimizationPage",
    "meta": {
      "title": "React Performance Optimization Techniques",
      "category": "FRONTEND",
      "date": "Oct 5, 2025",
      "readTime": "6 min read",
      "author": "Niraj Kamal K",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1711599813951-89297e6201a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RpbmclMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzYwODI4MTkxfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "tags": [
        "React",
        "Performance",
        "Optimization",
        "Frontend"
      ],
      "slug": "react-performance-optimization",
      "excerpt": "Discover advanced patterns and techniques to make your React applications blazingly fast and responsive.",
      "featuredOnHome": false,
      "featuredOnBlog": false,
      "displayOrder": 3,
      "external": false,
      "externalUrl": null
    }
  },
  {
    "slug": "tu-dresden-summer-2020",
    "component": null,
    "meta": {
      "title": "Summer 2020 Diaries: TU Dresden",
      "category": "ARCHITECTURE & RESEARCH",
      "date": "Dec 11, 2020",
      "readTime": "8 min read",
      "author": "Niraj K. Karunanidhi",
      "authorAvatar": "/Niraj_Photo.png",
      "heroImage": "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
      "tags": [
        "Architecture",
        "TU Dresden",
        "DAAD",
        "Research"
      ],
      "slug": "tu-dresden-summer-2020",
      "excerpt": "Reflections on my summer internship at TU Dresden's Knowledge Architecture Laboratory, working on digital and programmable architecture during the COVID-19 pandemic.",
      "featuredOnHome": true,
      "featuredOnBlog": true,
      "displayOrder": 2,
      "external": true,
      "externalUrl": "https://watchout.iitr.ac.in/2020/12/summer-diaries-TU-Dresden",
      "active": true
    }
  }
];

// Import all generated blog page components
import { BuildingScalableMicroservicesPage } from "./BuildingScalableMicroservicesPage";
import { PytorchCertificationCoursePage } from "./PytorchCertificationCoursePage";
import { ReactPerformanceOptimizationPage } from "./ReactPerformanceOptimizationPage";

export const BLOG_COMPONENTS = {
  "building-scalable-microservices": BuildingScalableMicroservicesPage,
  "pytorch-certification-course": PytorchCertificationCoursePage,
  "react-performance-optimization": ReactPerformanceOptimizationPage,
};
