// Auto-generated project index
// This file is automatically generated by build_projects.py
// Do not edit manually

export interface ProjectMeta {
  title: string;
  category: string;
  date: string;
  company?: string;
  location?: string;
  type?: string;
  heroImage?: string;
  tags: string[];
  github?: string;
  demo?: string;
  technologies?: string[];
  team?: string[];
  duration?: string;
  slug: string;
  description?: string;
  featuredOnHome?: boolean;
  featuredOnProjects?: boolean;
  displayOrder?: number;
  active?: boolean;
}

export interface ProjectIndexItem {
  slug: string;
  meta: ProjectMeta;
}

// Import all project page components
import { AdasValidationSimulationPage } from "./AdasValidationSimulationPage";
import { IbmFoundationModelsContributionPage } from "./IbmFoundationModelsContributionPage";
import { ProprietaryLlmDevelopmentPage } from "./ProprietaryLlmDevelopmentPage";

// Project index with metadata
export const PROJECT_INDEX: ProjectIndexItem[] = [
  {
    "slug": "adas-validation-simulation",
    "meta": {
      "title": "ADAS Validation and Verification Simulation",
      "category": "AUTONOMOUS SYSTEMS",
      "date": "Summer 2024",
      "company": "Automotive Research Lab",
      "location": "Atlanta, GA",
      "type": "Research Project",
      "heroImage": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
      "tags": [
        "ADAS",
        "Simulation",
        "Stochastic Methods",
        "Adversarial Models",
        "Autonomous Driving"
      ],
      "github": "https://github.com/example/adas-simulation",
      "demo": "https://adas-sim-demo.example.com",
      "technologies": [
        "Python",
        "CARLA",
        "ROS2",
        "Machine Learning",
        "Computer Vision"
      ],
      "team": [
        "Research Team",
        "Industry Partners"
      ],
      "duration": "4 months",
      "slug": "adas-validation-simulation",
      "description": "Developed simulations for verification and validation of ADAS features using stochastic methods and adversarial models.",
      "featuredOnHome": true,
      "featuredOnProjects": true,
      "displayOrder": 2
    }
  },

  {
    "slug": "ibm-foundation-models-contribution",
    "meta": {
      "title": "IBM Foundation Models Stack Enhancement",
      "category": "OPEN SOURCE",
      "date": "Summer 2024",
      "company": "IBM Research",
      "location": "Remote",
      "type": "Internship",
      "heroImage": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
      "tags": [
        "PyTorch",
        "Attention Mechanisms",
        "Open Source",
        "Foundation Models",
        "IBM"
      ],
      "github": "https://github.com/foundation-model-stack/foundation-model-stack",
      "demo": "https://fms.example.com",
      "technologies": [
        "PyTorch",
        "Python",
        "Transformers",
        "CUDA",
        "Git"
      ],
      "team": [
        "IBM Research Team",
        "Open Source Community"
      ],
      "duration": "3 months",
      "slug": "ibm-foundation-models-contribution",
      "description": "Enhanced IBM's Foundation Models Stack with optimized attention mechanisms and contributed to PyTorch core.",
      "featuredOnHome": false,
      "featuredOnProjects": false,
      "displayOrder": 3,
      "active": false
    }
  },
  {
    "slug": "proprietary-llm-development",
    "meta": {
      "title": "Proprietary Large Language Model Development",
      "category": "MACHINE LEARNING",
      "date": "Jan 2024 - Present",
      "company": "Stealth AI Startup",
      "location": "Atlanta, GA",
      "type": "Full-time",
      "heroImage": "https://images.unsplash.com/photo-1677442136019-21780ecad995?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
      "tags": [
        "LLM",
        "PyTorch",
        "CUDA",
        "Distributed Training",
        "A100"
      ],
      "github": "https://github.com/example/llm-project",
      "demo": "https://llm-demo.example.com",
      "technologies": [
        "PyTorch",
        "CUDA",
        "Python",
        "Distributed Computing",
        "A100 GPUs"
      ],
      "team": [
        "Lead ML Engineer",
        "Research Team",
        "Infrastructure Team"
      ],
      "duration": "8 months",
      "slug": "proprietary-llm-development",
      "description": "Led the development of a proprietary in-house Large Language Model, executing parallel distributed training on 8 Nvidia A100 GPUs.",
      "featuredOnHome": true,
      "featuredOnProjects": false,
      "displayOrder": 1
    }
  }
];

// Project components mapping
export const PROJECT_COMPONENTS = {
  "adas-validation-simulation": AdasValidationSimulationPage,
  "ibm-foundation-models-contribution": IbmFoundationModelsContributionPage,
  "proprietary-llm-development": ProprietaryLlmDevelopmentPage,
};
